spring:
  application:
    name: spring-redis
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: false
  data:
    redis:
      port: 6379
      host: localhost
jwt:
  secret-key: hello-test-secret-key-test-world
  access-token-expire: 10000 # 10000(10sec) 120000(2min)
  refresh-token-expire: 600000 # 10min